# Generated by Django 4.2.11 on 2024-05-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_music", "0002_allmusic_duration_allmusic_file_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="myMusic",
            field=models.ManyToManyField(
                blank=True, to="my_music.allmusic", verbose_name="Music:"
            ),
        ),
    ]
