# Generated by Django 5.0.5 on 2024-05-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_mymusic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_search_query',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
