# Generated by Django 5.0.5 on 2024-05-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_search_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='music_search_id',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
