# Generated by Django 4.2.11 on 2024-05-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allmusic",
            name="duration",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="allmusic",
            name="file",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="allmusic",
            name="author",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="allmusic",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
